accepted = [
    "AGPL-3.0",
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "CC0-1.0",
    "CDLA-Permissive-2.0",
    "ISC",
    "MIT",
    "OpenSSL",
    "Unicode-3.0",
    "Zlib"
]

no-clearly-defined = true

workarounds = [
    "ring"
]
