[package]
name = "directory"
version = "0.9.0"
authors = ["El RIDO <elrido@gmx.net>"]
edition = "2021"
license = "AGPL-3.0"

[dependencies]
diesel_migrations = "1.4.0"
dns-lookup = "1.0.8"
futures = "0.3.19"
isocountry = "0.3.2"
lazy_static = "1.4.0"
maxminddb = "0.21.0"
rand = "0.8.4"
regex = "1.5.4"
tokio = "1.15.0"
url = "2.2.2"

[dependencies.diesel]
version = "1.4.8"
features = ["sqlite"]

[dependencies.hyper]
version = "0.14.16"
features = ["client"]

[dependencies.hyper-rustls]
version = "0.23.0"
default-features = false
features = ["native-tokio", "http1", "http2", "tls12", "webpki-tokio"]

[dependencies.libsqlite3-sys] # included for the static binary to link it in
version = "0.22.2" # this version needs to be compatible with diesel
features = ["bundled"]

[dependencies.rocket]
version = "0.5.0-rc.1"
features = ["json"]

[dependencies.rocket_dyn_templates]
version = "0.1.0-rc.1"
features = ["tera"]

[dependencies.rocket_sync_db_pools]
version = "0.1.0-rc.1"
features = ["diesel_sqlite_pool"]

[profile.release]
opt-level = 'z'  # Optimize for size.
lto = true
codegen-units = 1
