[package]
name = "directory"
version = "0.10.5"
authors = ["El RIDO <elrido@gmx.net>"]
edition = "2021"
license = "AGPL-3.0"
rust-version = "1.66"

[dependencies]
diesel_migrations = "2.1.0"
futures = "0.3.29"
isocountry = "0.3.2"
lazy_static = "1.4.0"
maxminddb = "0.23.0"
rand = "0.8.5"
regex = "1.10.2"
tokio = "1.34.0"
url = "2.4.1"

[dependencies.diesel]
version = "2.1.4"
features = ["sqlite"]

[dependencies.hyper]
version = "1.0.1"
features = ["client"]

[dependencies.hyper-rustls]
version = "0.24.2"
default-features = false
features = ["http1", "http2", "tls12", "webpki-tokio"]

[dependencies.rocket]
version = "0.5.0"
features = ["json"]

[dependencies.rocket_dyn_templates]
version = "0.1.0"
features = ["tera"]

[dependencies.rocket_sync_db_pools]
version = "0.1.0"
features = ["diesel_sqlite_pool"]

[profile.release]
opt-level = 'z'  # Optimize for size.
lto = true
codegen-units = 1
strip = true
