[package]
name = "directory"
version = "0.6.0"
authors = ["El RIDO <elrido@gmx.net>"]
edition = "2018"
license = "AGPL-3.0"

[dependencies]
diesel_migrations = "1.4.0"
dns-lookup = "1.0.8"
hyper = "0.10.16"
hyper-timeout-connector = "0.1.0"
isocountry = "0.3.2"
lazy_static = "1.4.0"
maxminddb = "0.21.0"
rand = "0.8.4"
regex = "1.5.4"
rocket = "0.4.7"
serde_json = "1.0.64"

[dependencies.diesel]
version = "1.4.7"
features = ["sqlite"]

[dependencies.hyper-sync-rustls]
version = "0.3.0-rc.17"
default-features = false
features = ["client"]

[dependencies.libsqlite3-sys] # included for the static binary to link it in
version = "0.22.2"
features = ["bundled"]

[dependencies.rocket_contrib]
version = "0.4.7"
default-features = false
features = ["diesel_sqlite_pool", "json", "serve", "tera_templates"]

[dependencies.serde]
version = "1.0.126"
features = ["derive"]

[profile.release]
opt-level = 'z'  # Optimize for size.
lto = true
codegen-units = 1
