[package]
name = "directory"
version = "0.10.8"
authors = ["El RIDO <elrido@gmx.net>"]
edition = "2021"
license = "AGPL-3.0"
rust-version = "1.70"

[dependencies]
diesel_migrations = "2.1.0"
futures = "0.3.30"
http-body-util = "0.1.1"
hyper-util = "0.1.3"
isocountry = "0.3.2"
maxminddb = "0.24.0"
rand = "0.8.5"
regex = "1.10.4"
tokio = "1.37.0"
url = "2.5.0"

[dependencies.diesel]
version = "2.1.6"
features = ["sqlite"]

[dependencies.hyper]
version = "1.3.1"
features = ["client"]

[dependencies.hyper-rustls]
version = "0.27.1"
default-features = false
features = ["http1", "http2", "tls12", "ring", "webpki-tokio"]

[dependencies.rocket]
version = "0.5.1"
features = ["json"]

[dependencies.rocket_dyn_templates]
version = "0.1.0"
features = ["tera"]

[dependencies.rocket_sync_db_pools]
version = "0.1.0"
features = ["diesel_sqlite_pool"]

[profile.release]
opt-level = 'z'  # Optimize for size.
lto = true
codegen-units = 1
strip = true
