name: Build & Deploy Docker Image

on:
  push:
    tags: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prepare
        id: prepare
        run: |
          echo ::set-output name=version::${GITHUB_REF##*/}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Docker Login
        uses: docker/login-action@v1
        with:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker Build and Push
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64
          push: true
          tags:
            - privatebin/directory:${{ steps.prepare.outputs.version }}
            - privatebin/directory:latest

